development:
  adapter: sqlite3
  database: db/dev.sqlite3
  pool: 5
  username: root

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  username: root

production: 
  database: ENV['RDS_DB_NAME']
  username: ENV['RDS_USERNAME']
  password: ENV['RDS_PASSWORD']
  hostname: ENV['RDS_HOSTNAME']
  port: ENV['RDS_PORT']